/**
 * Created by JOYyuan on 16/11/6.
 */
$(document).ready(function(){
    $("#m_index").click(function(){
        window.location.href="index.html"
    });
    $("#m_groups").click(function(){
        window.location.href="groups.html";
    });
    $("#m_proc").click(function(){
        window.location.href="process.html";
    });
    $("#m_dian").click(function(){
        window.open('http://dian.hust.edu.cn','_blank');
    });
    $("#m_join").click(function(){
        window.location.href="arrange.html";
    });
});